### PR TITLE
#514 - Updated FAST subjects YAML data

### PR DESCRIPTION
**Pull request by chrispeacockbl**

### CODE REVIEW

**Comment by anjackson** [comment]
Please note question/comment on one part.

**Comment by chrispeacockbl** [comment]
I was going by the issue's attached document. 
Row 60:
 International agencies 	fst00971852						

Are there errors in this?

**Comment by anjackson** [comment]
Hum, yes, it appears so.

**Comment by chrispeacockbl** [comment]
Is there an easy (non-manual) way to check these against the definitive source?

**Comment by nicolabingham** [comment]
HI Chris, I will double check the list and get back to you.

**Comment by anjackson** [comment]
Technically you can [download](http://www.oclc.org/research/themes/data-science/fast/download.html) some or all of the dataset, or I think there are [linked data APIs](http://experimental.worldcat.org/fast/) you can use.

**Comment by nicolabingham** [comment]
I've double checked the list against the official database (http://fast.oclc.org/searchfast/). It seems that 'International relations' and 'industries' had the wrong codes against them but the rest of the spreadsheet is correct. Apologies for this error. The corrected file is attached 
[FAST_subject_headings-2.xlsx](https://github.com/ukwa/w3act/files/300534/FAST_subject_headings-2.xlsx)

**Comment by chrispeacockbl** [comment]
That should be 'International agencies' ;-) 
Thanks.

**Comment by nicolabingham** [comment]
Thanks Chris :)

**Comment by chrispeacockbl** [comment]
Done, please see Pull Request #517.

**Pull request merged**
