### PR TITLE
issue-576

### PR DESCRIPTION
**Pull request by min2ha**
issue-576 fix (commenting complex part)

### CODE REVIEW

**Comment by anjackson** [comment]
This looks good, BTW. Minor issue is that our development evironments appear to be treating whitespace/indents differently which is causing a lot of 'noise' to appear when looking at the changes.

I think we use four spaces rather than tabs. Are you using tabs?

**Comment by min2ha** [comment]
@anjackson, sorry, it depends on type of file. Usually I’m just trying precisely to match the structure of new add lines hierarchy according to previous lines. So in java code files I'm using tabs, but sometimes in file types like HTML templates or configuration files I’m forced to use just spaces in order to look same style, which was previously applied. Could you point me which files exactly troubles you?

**Comment by anjackson** [comment]
@min2ha I mean all the files touched in this commit (see 'Files updated' tab). Are you okay to switch to spaces rather than tabs for UKWA work?

**Comment by min2ha** [comment]
@anjackson, yes, I can switch to spaces, no probs.

**Comment by anjackson** [comment]
@min2ha thanks. The templates appear to be a bit of a mess whitespace-wise, but at least we got the Java neatened up a bit! Thanks.

**Comment by min2ha** [comment]
@anjackson, you are right, I just noticed, that IntelliJ IDEA IDE new line tab spacing sometimes differs from previous context template.

**Comment by chrispeacockbl** [comment]
@min2ha I don't know whether there is an option to always ask that you've perhaps overridden, but I usually get a prompt in the top of my editor windows saying something like "This file is indented with tabs. Use spaces instead?" to which I respond 'yes'.

**Comment by min2ha** [comment]
Now I many tab/space issues. Trying to fix ASAP.

**Comment by min2ha** [comment]
@anjackson, I've converted indents to spaces for all files I've modified for issue fixes/enhancements. Now it is less mess.

**Comment by anjackson** [comment]
Okay, thanks.

**Pull request merged**
